[2022-12-17T11:03:44.890+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-17T11:03:40.047396+00:00 [queued]>
[2022-12-17T11:03:44.905+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-17T11:03:40.047396+00:00 [queued]>
[2022-12-17T11:03:44.905+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T11:03:45.047+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-17T11:03:45.049+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T11:03:45.101+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): encoding> on 2022-12-17 11:03:40.047396+00:00
[2022-12-17T11:03:45.107+0000] {standard_task_runner.py:55} INFO - Started process 1929 to run task
[2022-12-17T11:03:45.111+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'titanic_etl_pipeline', 'encoding', 'manual__2022-12-17T11:03:40.047396+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/titanic_etl.py', '--cfg-path', '/tmp/tmpu_h3q0qe']
[2022-12-17T11:03:45.113+0000] {standard_task_runner.py:83} INFO - Job 108: Subtask encoding
[2022-12-17T11:03:45.185+0000] {task_command.py:389} INFO - Running <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-17T11:03:40.047396+00:00 [running]> on host 3b51f8facfba
[2022-12-17T11:03:45.277+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=titanic_etl_pipeline
AIRFLOW_CTX_TASK_ID=encoding
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T11:03:40.047396+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T11:03:40.047396+00:00
[2022-12-17T11:03:45.279+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/titanic_etl.py", line 23, in encode_load
    df = pd.read_csv(filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/titanic_clean.csv'
[2022-12-17T11:03:45.294+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=titanic_etl_pipeline, task_id=encoding, execution_date=20221217T110340, start_date=20221217T110344, end_date=20221217T110345
[2022-12-17T11:03:45.308+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 108 for task encoding ([Errno 2] No such file or directory: '/opt/airflow/data/titanic_clean.csv'; 1929)
[2022-12-17T11:03:45.323+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-17T11:03:45.357+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
