[2022-12-16T21:49:03.233+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-16T21:48:55.356905+00:00 [queued]>
[2022-12-16T21:49:03.281+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-16T21:48:55.356905+00:00 [queued]>
[2022-12-16T21:49:03.284+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T21:49:03.293+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-16T21:49:03.295+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T21:49:03.387+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): encoding> on 2022-12-16 21:48:55.356905+00:00
[2022-12-16T21:49:03.407+0000] {standard_task_runner.py:55} INFO - Started process 645 to run task
[2022-12-16T21:49:03.426+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'titanic_etl_pipeline', 'encoding', 'manual__2022-12-16T21:48:55.356905+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/titanic_etl.py', '--cfg-path', '/tmp/tmpeu_l74vk']
[2022-12-16T21:49:03.437+0000] {standard_task_runner.py:83} INFO - Job 50: Subtask encoding
[2022-12-16T21:49:03.662+0000] {task_command.py:389} INFO - Running <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-16T21:48:55.356905+00:00 [running]> on host fc16b2a5d81d
[2022-12-16T21:49:03.883+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=titanic_etl_pipeline
AIRFLOW_CTX_TASK_ID=encoding
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T21:48:55.356905+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T21:48:55.356905+00:00
[2022-12-16T21:49:03.887+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: encoding() missing 1 required positional argument: 'df'
[2022-12-16T21:49:03.905+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=titanic_etl_pipeline, task_id=encoding, execution_date=20221216T214855, start_date=20221216T214903, end_date=20221216T214903
[2022-12-16T21:49:03.945+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 50 for task encoding (encoding() missing 1 required positional argument: 'df'; 645)
[2022-12-16T21:49:04.002+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-16T21:49:04.128+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
