[2022-12-10T03:23:24.102+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_python_operator.log_sql_query manual__2022-12-10T03:23:20.045919+00:00 [queued]>
[2022-12-10T03:23:24.129+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: example_python_operator.log_sql_query manual__2022-12-10T03:23:20.045919+00:00 [queued]>
[2022-12-10T03:23:24.130+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-10T03:23:24.131+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-10T03:23:24.132+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-10T03:23:24.192+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): log_sql_query> on 2022-12-10 03:23:20.045919+00:00
[2022-12-10T03:23:24.202+0000] {standard_task_runner.py:55} INFO - Started process 326 to run task
[2022-12-10T03:23:24.208+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'example_python_operator', 'log_sql_query', 'manual__2022-12-10T03:23:20.045919+00:00', '--job-id', '1185', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_python_operator.py', '--cfg-path', '/tmp/tmpgrlc3y5r']
[2022-12-10T03:23:24.210+0000] {standard_task_runner.py:83} INFO - Job 1185: Subtask log_sql_query
[2022-12-10T03:23:24.341+0000] {task_command.py:389} INFO - Running <TaskInstance: example_python_operator.log_sql_query manual__2022-12-10T03:23:20.045919+00:00 [running]> on host 3ce06e55ea30
[2022-12-10T03:23:24.407+0000] {abstractoperator.py:596} ERROR - Exception rendering Jinja template for task 'log_sql_query', field 'templates_dict'. Template: {'query': 'sql/sample.sql'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/sample.sql
[2022-12-10T03:23:24.410+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1378, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1497, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2119, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1196, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 589, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 640, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: sql/sample.sql
[2022-12-10T03:23:24.425+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=example_python_operator, task_id=log_sql_query, execution_date=20221210T032320, start_date=20221210T032324, end_date=20221210T032324
[2022-12-10T03:23:24.451+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1185 for task log_sql_query (sql/sample.sql; 326)
[2022-12-10T03:23:24.499+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-10T03:23:24.557+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
