[2022-12-16T23:20:58.830+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2022-12-16T23:20:48.161643+00:00 [queued]>
[2022-12-16T23:20:58.849+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2022-12-16T23:20:48.161643+00:00 [queued]>
[2022-12-16T23:20:58.850+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T23:20:58.851+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-16T23:20:58.851+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T23:20:58.881+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): create_dashboard_task> on 2022-12-16 23:20:48.161643+00:00
[2022-12-16T23:20:58.889+0000] {standard_task_runner.py:55} INFO - Started process 5246 to run task
[2022-12-16T23:20:58.894+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'titanic_etl_pipeline', 'create_dashboard_task', 'manual__2022-12-16T23:20:48.161643+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/titanic_etl.py', '--cfg-path', '/tmp/tmp8drsqr6w']
[2022-12-16T23:20:58.897+0000] {standard_task_runner.py:83} INFO - Job 101: Subtask create_dashboard_task
[2022-12-16T23:20:59.016+0000] {task_command.py:389} INFO - Running <TaskInstance: titanic_etl_pipeline.create_dashboard_task manual__2022-12-16T23:20:48.161643+00:00 [running]> on host 14c90533c456
[2022-12-16T23:20:59.207+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=titanic_etl_pipeline
AIRFLOW_CTX_TASK_ID=create_dashboard_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T23:20:48.161643+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T23:20:48.161643+00:00
[2022-12-16T23:20:59.261+0000] {logging_mixin.py:137} INFO - Dash is running on http://0.0.0.0:8050/
[2022-12-16T23:20:59.260+0000] {dash.py:1968} INFO - Dash is running on http://0.0.0.0:8050/

[2022-12-16T23:20:59.277+0000] {logging_mixin.py:137} INFO -  * Serving Flask app '***'
[2022-12-16T23:20:59.278+0000] {logging_mixin.py:137} INFO -  * Debug mode: off
[2022-12-16T23:20:59.280+0000] {_internal.py:224} INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8050
 * Running on http://192.168.16.3:8050
[2022-12-16T23:20:59.281+0000] {_internal.py:224} INFO - [33mPress CTRL+C to quit[0m
[2022-12-16T23:21:23.822+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:23] "GET / HTTP/1.1" 200 -
[2022-12-16T23:21:24.018+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/deps/react@16.v2_7_1m1671229013.14.0.min.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.022+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/deps/polyfill@7.v2_7_1m1671229013.12.1.min.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.030+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_7_1m1671229013.14.0.min.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.033+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_7_1m1671229013.8.1.min.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.038+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/dcc/dash_core_components.v2_7_1m1671229013.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.047+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_7_1m1671229013.min.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.059+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/html/dash_html_components.v2_0_7m1671229013.min.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.060+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/dcc/dash_core_components-shared.v2_7_1m1671229013.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.077+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/dash_table/bundle.v5_2_1m1671229013.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.483+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-dependencies HTTP/1.1" 200 -
[2022-12-16T23:21:24.487+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-layout HTTP/1.1" 200 -
[2022-12-16T23:21:24.837+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.858+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1" 200 -
[2022-12-16T23:21:24.862+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:24] "GET /_favicon.ico?v=2.7.1 HTTP/1.1" 200 -
[2022-12-16T23:21:51.233+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:51] "GET / HTTP/1.1" 200 -
[2022-12-16T23:21:51.970+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:51] "GET /_dash-layout HTTP/1.1" 200 -
[2022-12-16T23:21:51.973+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:51] "GET /_dash-dependencies HTTP/1.1" 200 -
[2022-12-16T23:21:52.363+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:52] "[36mGET /_dash-component-suites/dash/dcc/async-graph.js HTTP/1.1[0m" 304 -
[2022-12-16T23:21:52.376+0000] {_internal.py:224} INFO - 192.168.16.1 - - [16/Dec/2022 23:21:52] "[36mGET /_dash-component-suites/dash/dcc/async-plotlyjs.js HTTP/1.1[0m" 304 -
[2022-12-16T23:54:45.321+0000] {local_task_job.py:82} ERROR - Received SIGTERM. Terminating subprocesses
[2022-12-16T23:54:45.331+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 5246. PIDs of all processes in the group: [5246]
[2022-12-16T23:54:45.332+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 5246
[2022-12-16T23:54:45.334+0000] {taskinstance.py:1483} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-12-16T23:54:45.392+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/titanic_etl.py", line 84, in create_dashboard
    app.run_server(host='0.0.0.0')
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 2133, in run_server
    self.run(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/dash/dash.py", line 1980, in run
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 1098, in run_simple
    srv.serve_forever()
  File "/home/airflow/.local/lib/python3.7/site-packages/werkzeug/serving.py", line 741, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "/usr/local/lib/python3.7/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/local/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1485, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-12-16T23:54:45.413+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=titanic_etl_pipeline, task_id=create_dashboard_task, execution_date=20221216T232048, start_date=20221216T232058, end_date=20221216T235445
[2022-12-16T23:54:45.462+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 101 for task create_dashboard_task (Task received SIGTERM signal; 5246)
[2022-12-16T23:54:45.513+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=5246, status='terminated', exitcode=1, started='23:20:58') (5246) terminated with exit code 1
[2022-12-16T23:54:45.515+0000] {local_task_job.py:159} INFO - Task exited with return code 143
[2022-12-16T23:54:45.566+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
