[2022-12-16T21:50:59.137+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-16T21:50:51.122930+00:00 [queued]>
[2022-12-16T21:50:59.175+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-16T21:50:51.122930+00:00 [queued]>
[2022-12-16T21:50:59.178+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T21:50:59.180+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2022-12-16T21:50:59.182+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T21:50:59.252+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): encoding> on 2022-12-16 21:50:51.122930+00:00
[2022-12-16T21:50:59.268+0000] {standard_task_runner.py:55} INFO - Started process 1542 to run task
[2022-12-16T21:50:59.281+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'titanic_etl_pipeline', 'encoding', 'manual__2022-12-16T21:50:51.122930+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/titanic_etl.py', '--cfg-path', '/tmp/tmpqsf59q5g']
[2022-12-16T21:50:59.289+0000] {standard_task_runner.py:83} INFO - Job 52: Subtask encoding
[2022-12-16T21:50:59.560+0000] {task_command.py:389} INFO - Running <TaskInstance: titanic_etl_pipeline.encoding manual__2022-12-16T21:50:51.122930+00:00 [running]> on host fc16b2a5d81d
[2022-12-16T21:50:59.870+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=titanic_etl_pipeline
AIRFLOW_CTX_TASK_ID=encoding
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T21:50:51.122930+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T21:50:51.122930+00:00
[2022-12-16T21:50:59.879+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/titanic_etl.py", line 19, in encode_load
    df = pd.read_csv(filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/titanic_clean.csv'
[2022-12-16T21:50:59.971+0000] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=titanic_etl_pipeline, task_id=encoding, execution_date=20221216T215051, start_date=20221216T215059, end_date=20221216T215059
[2022-12-16T21:51:00.073+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 52 for task encoding ([Errno 2] No such file or directory: '/opt/airflow/data/titanic_clean.csv'; 1542)
[2022-12-16T21:51:00.137+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-16T21:51:00.183+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
