[2022-12-15T12:11:48.410+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:11:48.412+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:11:48.414+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:11:48.414+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:11:50.455+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:11:50.447+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:11:50.459+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:11:50.489+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 2.086 seconds
[2022-12-15T12:12:20.574+0000] {processor.py:153} INFO - Started process (PID=443) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:12:20.576+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:12:20.577+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:12:20.577+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:12:21.548+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:12:21.541+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:12:21.550+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:12:21.589+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 1.021 seconds
[2022-12-15T12:12:52.202+0000] {processor.py:153} INFO - Started process (PID=674) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:12:52.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:12:52.210+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:12:52.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:12:52.792+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:12:52.783+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:12:52.794+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:12:52.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.657 seconds
[2022-12-15T12:13:22.971+0000] {processor.py:153} INFO - Started process (PID=902) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:13:22.973+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:13:22.975+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:13:22.974+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:13:23.563+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:13:23.555+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:13:23.566+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:13:23.597+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.631 seconds
[2022-12-15T12:13:53.852+0000] {processor.py:153} INFO - Started process (PID=1133) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:13:53.853+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:13:53.855+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:13:53.855+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:13:54.401+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:13:54.393+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:13:54.404+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:13:54.441+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.595 seconds
[2022-12-15T12:14:24.783+0000] {processor.py:153} INFO - Started process (PID=1369) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:14:24.786+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:14:24.788+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:14:24.787+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:14:25.674+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:14:25.661+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:14:25.677+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:14:25.725+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.955 seconds
[2022-12-15T12:14:56.035+0000] {processor.py:153} INFO - Started process (PID=1614) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:14:56.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:14:56.038+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:14:56.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:14:56.591+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:14:56.582+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:14:56.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:14:56.632+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.603 seconds
[2022-12-15T12:15:26.783+0000] {processor.py:153} INFO - Started process (PID=1846) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:15:26.784+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:15:26.786+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:15:26.786+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:15:27.360+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:15:27.353+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:15:27.363+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:15:27.400+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.622 seconds
[2022-12-15T12:17:05.144+0000] {processor.py:153} INFO - Started process (PID=177) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:17:05.146+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:17:05.147+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:17:05.147+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:17:05.765+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:17:05.757+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:17:05.768+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:17:05.820+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.689 seconds
[2022-12-15T12:17:36.100+0000] {processor.py:153} INFO - Started process (PID=407) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:17:36.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:17:36.103+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:17:36.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:17:36.767+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:17:36.759+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:17:36.770+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:17:36.802+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.707 seconds
[2022-12-15T12:18:07.035+0000] {processor.py:153} INFO - Started process (PID=651) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:18:07.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:18:07.038+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:18:07.038+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:18:07.597+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:18:07.590+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:18:07.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:18:07.629+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.600 seconds
[2022-12-15T12:18:37.913+0000] {processor.py:153} INFO - Started process (PID=886) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:18:37.915+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:18:37.919+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:18:37.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:18:38.600+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:18:38.592+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:18:38.604+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:18:38.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.742 seconds
[2022-12-15T12:19:08.939+0000] {processor.py:153} INFO - Started process (PID=1123) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:19:08.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:19:08.942+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:19:08.942+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:19:09.488+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:19:09.479+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:19:09.490+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:19:09.537+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.605 seconds
[2022-12-15T12:19:39.629+0000] {processor.py:153} INFO - Started process (PID=1357) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:19:39.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:19:39.632+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:19:39.632+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:19:40.180+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:19:40.172+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:19:40.182+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:19:40.221+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.597 seconds
[2022-12-15T12:20:10.374+0000] {processor.py:153} INFO - Started process (PID=1592) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:20:10.375+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:20:10.377+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:20:10.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:20:10.972+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:20:10.963+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:20:10.975+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:20:11.007+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.639 seconds
[2022-12-15T12:20:41.169+0000] {processor.py:153} INFO - Started process (PID=1824) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:20:41.171+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:20:41.172+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:20:41.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:20:41.763+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:20:41.752+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:20:41.765+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:20:41.812+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.649 seconds
[2022-12-15T12:21:12.097+0000] {processor.py:153} INFO - Started process (PID=2057) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:21:12.098+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:21:12.100+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:21:12.099+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:21:12.660+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:21:12.652+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:21:12.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:21:12.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.603 seconds
[2022-12-15T12:21:43.054+0000] {processor.py:153} INFO - Started process (PID=2291) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:21:43.055+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:21:43.057+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:21:43.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:21:43.639+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:21:43.628+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:21:43.642+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:21:43.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.650 seconds
[2022-12-15T12:22:13.813+0000] {processor.py:153} INFO - Started process (PID=2522) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:22:13.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:22:13.817+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:22:13.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:22:14.505+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:22:14.497+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:22:14.508+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:22:14.553+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.745 seconds
[2022-12-15T12:22:44.636+0000] {processor.py:153} INFO - Started process (PID=2753) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:22:44.638+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:22:44.639+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:22:44.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:22:45.192+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:22:45.182+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:22:45.195+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:22:45.236+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.607 seconds
[2022-12-15T12:23:15.317+0000] {processor.py:153} INFO - Started process (PID=2984) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:23:15.319+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:23:15.321+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:23:15.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:23:15.865+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:23:15.855+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:23:15.868+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:23:15.903+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.591 seconds
[2022-12-15T12:23:46.121+0000] {processor.py:153} INFO - Started process (PID=3218) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:23:46.123+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:23:46.125+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:23:46.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:23:46.626+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:23:46.618+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:23:46.629+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:23:46.667+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.551 seconds
[2022-12-15T12:24:17.138+0000] {processor.py:153} INFO - Started process (PID=3447) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:24:17.140+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:24:17.142+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:24:17.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:24:17.712+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:24:17.703+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:24:17.714+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:24:17.753+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.623 seconds
[2022-12-15T12:24:48.077+0000] {processor.py:153} INFO - Started process (PID=3682) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:24:48.079+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:24:48.080+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:24:48.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:24:49.311+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:24:49.300+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:24:49.314+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:29:06.356+0000] {processor.py:153} INFO - Started process (PID=186) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:29:06.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:29:06.360+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:29:06.360+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:29:08.481+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:29:08.472+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:29:08.484+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:29:08.516+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 2.167 seconds
[2022-12-15T12:29:38.668+0000] {processor.py:153} INFO - Started process (PID=442) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:29:38.670+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:29:38.671+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:29:38.671+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:29:39.192+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:29:39.183+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:29:39.195+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:29:39.232+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.569 seconds
[2022-12-15T12:30:09.310+0000] {processor.py:153} INFO - Started process (PID=675) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:30:09.311+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:30:09.313+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:30:09.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:30:09.909+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:30:09.898+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:30:09.911+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:30:09.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.654 seconds
[2022-12-15T12:30:40.745+0000] {processor.py:153} INFO - Started process (PID=909) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:30:40.747+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:30:40.748+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:30:40.748+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:30:41.305+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:30:41.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:30:41.307+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:30:41.352+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.613 seconds
[2022-12-15T12:31:11.482+0000] {processor.py:153} INFO - Started process (PID=1140) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:31:11.485+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:31:11.487+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:31:11.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:31:12.081+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:31:12.073+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:31:12.083+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:31:12.123+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.654 seconds
[2022-12-15T12:31:42.390+0000] {processor.py:153} INFO - Started process (PID=1370) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:31:42.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:31:42.394+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:31:42.394+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:31:42.970+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:31:42.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:31:42.973+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:31:43.020+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.638 seconds
[2022-12-15T12:32:13.136+0000] {processor.py:153} INFO - Started process (PID=1608) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:32:13.138+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:32:13.140+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:32:13.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:32:13.701+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:32:13.691+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:32:13.704+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:32:13.769+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.638 seconds
[2022-12-15T12:32:44.031+0000] {processor.py:153} INFO - Started process (PID=1842) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:32:44.033+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:32:44.034+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:32:44.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:32:44.591+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:32:44.582+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:32:44.593+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:32:44.643+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.617 seconds
[2022-12-15T12:33:14.729+0000] {processor.py:153} INFO - Started process (PID=2075) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:33:14.730+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:33:14.732+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:33:14.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:33:15.299+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:33:15.291+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:33:15.301+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:33:15.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.614 seconds
[2022-12-15T12:33:45.722+0000] {processor.py:153} INFO - Started process (PID=2316) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:33:45.724+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:33:45.725+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:33:45.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:33:46.311+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:33:46.303+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:33:46.313+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:33:46.350+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.634 seconds
[2022-12-15T12:34:16.649+0000] {processor.py:153} INFO - Started process (PID=2548) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:34:16.651+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:34:16.652+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:34:16.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:34:17.258+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:34:17.248+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:34:17.261+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:34:17.301+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.659 seconds
[2022-12-15T12:34:47.484+0000] {processor.py:153} INFO - Started process (PID=2784) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:34:47.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:34:47.487+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:34:47.487+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:34:47.973+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:34:47.963+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:34:47.976+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:34:48.010+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.531 seconds
[2022-12-15T12:35:18.860+0000] {processor.py:153} INFO - Started process (PID=3018) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:35:18.862+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:35:18.863+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:35:18.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:35:19.386+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:35:19.377+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:35:19.388+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:35:19.427+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.574 seconds
[2022-12-15T12:35:50.093+0000] {processor.py:153} INFO - Started process (PID=3248) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:35:50.095+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:35:50.096+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:35:50.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:35:50.618+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:35:50.610+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:35:50.621+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:35:50.659+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.572 seconds
[2022-12-15T12:36:21.047+0000] {processor.py:153} INFO - Started process (PID=3477) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:36:21.049+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:36:21.051+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:36:21.050+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:36:21.721+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:36:21.713+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:36:21.724+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:36:21.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.714 seconds
[2022-12-15T12:36:51.909+0000] {processor.py:153} INFO - Started process (PID=3710) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:36:51.911+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:36:51.913+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:36:51.913+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:36:52.973+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:36:52.963+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:36:52.975+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:36:53.021+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 1.118 seconds
[2022-12-15T12:37:23.245+0000] {processor.py:153} INFO - Started process (PID=3948) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:37:23.246+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:37:23.248+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:37:23.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:37:23.737+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:37:23.728+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:37:23.740+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:37:23.780+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.540 seconds
[2022-12-15T12:37:54.585+0000] {processor.py:153} INFO - Started process (PID=4185) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:37:54.587+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:37:54.589+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:37:54.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:37:55.170+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:37:55.161+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:37:55.172+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:37:55.213+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.633 seconds
[2022-12-15T12:38:25.661+0000] {processor.py:153} INFO - Started process (PID=4415) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:38:25.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:38:25.668+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:38:25.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:38:26.335+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:38:26.326+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:38:26.337+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:38:26.376+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.723 seconds
[2022-12-15T12:38:56.634+0000] {processor.py:153} INFO - Started process (PID=4643) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:38:56.635+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:38:56.637+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:38:56.636+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:38:57.306+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:38:57.297+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:38:57.309+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:38:57.342+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.714 seconds
[2022-12-15T12:39:27.470+0000] {processor.py:153} INFO - Started process (PID=4885) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:39:27.471+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:39:27.473+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:39:27.472+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:39:28.019+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:39:28.011+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:39:28.021+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:39:28.065+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.602 seconds
[2022-12-15T12:39:58.148+0000] {processor.py:153} INFO - Started process (PID=5119) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:39:58.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:39:58.152+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:39:58.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:39:58.729+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:39:58.719+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:39:58.732+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:39:58.771+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.628 seconds
[2022-12-15T12:40:29.710+0000] {processor.py:153} INFO - Started process (PID=5348) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:40:29.714+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:40:29.717+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:40:29.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:40:30.251+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:40:30.242+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:40:30.254+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:40:30.293+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.598 seconds
[2022-12-15T12:41:00.970+0000] {processor.py:153} INFO - Started process (PID=5577) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:41:00.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:41:00.973+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:41:00.973+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:41:01.581+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:41:01.482+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:41:01.588+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:41:01.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.713 seconds
[2022-12-15T12:41:31.980+0000] {processor.py:153} INFO - Started process (PID=5816) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:41:31.982+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:41:31.983+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:41:31.983+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:41:32.588+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:41:32.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:41:32.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:41:32.667+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.693 seconds
[2022-12-15T12:42:02.757+0000] {processor.py:153} INFO - Started process (PID=6050) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:42:02.759+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:42:02.760+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:42:02.760+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:42:03.275+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:42:03.266+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:42:03.278+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:42:03.310+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.557 seconds
[2022-12-15T12:42:33.627+0000] {processor.py:153} INFO - Started process (PID=6290) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:42:33.629+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:42:33.631+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:42:33.630+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:42:34.149+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:42:34.140+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:42:34.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:42:34.189+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.568 seconds
[2022-12-15T12:43:04.665+0000] {processor.py:153} INFO - Started process (PID=6526) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:43:04.667+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:43:04.669+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:43:04.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:43:05.225+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:43:05.216+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:43:05.228+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:43:05.264+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.607 seconds
[2022-12-15T12:43:35.523+0000] {processor.py:153} INFO - Started process (PID=6762) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:43:35.526+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:43:35.527+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:43:35.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:43:36.169+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:43:36.156+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:43:36.171+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:43:36.226+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.709 seconds
[2022-12-15T12:44:07.134+0000] {processor.py:153} INFO - Started process (PID=7003) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:44:07.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:44:07.140+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:44:07.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:44:07.945+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:44:07.938+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:44:07.947+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:44:07.979+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.851 seconds
[2022-12-15T12:44:38.634+0000] {processor.py:153} INFO - Started process (PID=7236) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:44:38.636+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:44:38.638+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:44:38.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:44:39.214+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:44:39.205+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:44:39.217+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:44:39.256+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.629 seconds
[2022-12-15T12:45:09.451+0000] {processor.py:153} INFO - Started process (PID=7468) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:45:09.453+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:45:09.454+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:45:09.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:45:10.041+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:45:10.031+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:45:10.045+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:45:10.098+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.654 seconds
[2022-12-15T12:45:40.319+0000] {processor.py:153} INFO - Started process (PID=7693) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:45:40.324+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:45:40.328+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:45:40.328+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:45:41.006+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:45:40.998+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:45:41.009+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:45:41.044+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.744 seconds
[2022-12-15T12:46:11.269+0000] {processor.py:153} INFO - Started process (PID=7923) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:46:11.270+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:46:11.272+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:46:11.271+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:46:11.848+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:46:11.839+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:46:11.851+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:46:11.890+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.627 seconds
[2022-12-15T12:46:42.161+0000] {processor.py:153} INFO - Started process (PID=8151) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:46:42.165+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:46:42.167+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:46:42.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:46:42.775+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:46:42.765+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:46:42.778+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:46:42.813+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.663 seconds
[2022-12-15T12:47:13.056+0000] {processor.py:153} INFO - Started process (PID=8384) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:47:13.058+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:47:13.059+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:47:13.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:47:13.563+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:47:13.553+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:47:13.566+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:47:13.599+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.548 seconds
[2022-12-15T12:47:43.641+0000] {processor.py:153} INFO - Started process (PID=8615) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:47:43.643+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:47:43.644+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:47:43.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:47:44.160+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:47:44.152+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:47:44.162+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:47:44.200+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.565 seconds
[2022-12-15T12:48:14.783+0000] {processor.py:153} INFO - Started process (PID=8851) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:48:14.786+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:48:14.788+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:48:14.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:48:15.536+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:48:15.526+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:48:15.539+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:48:15.591+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.815 seconds
[2022-12-15T12:48:45.806+0000] {processor.py:153} INFO - Started process (PID=9081) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:48:45.807+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:48:45.809+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:48:45.809+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:48:46.502+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:48:46.494+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:48:46.504+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:48:46.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.747 seconds
[2022-12-15T12:49:16.771+0000] {processor.py:153} INFO - Started process (PID=9315) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:49:16.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:49:16.776+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:49:16.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:49:17.463+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:49:17.452+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:49:17.466+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:49:17.507+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.743 seconds
[2022-12-15T12:49:47.628+0000] {processor.py:153} INFO - Started process (PID=9550) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:49:47.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:49:47.631+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:49:47.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:49:48.121+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:49:48.111+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:49:48.124+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:49:48.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.539 seconds
[2022-12-15T12:50:18.463+0000] {processor.py:153} INFO - Started process (PID=9783) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:50:18.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:50:18.468+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:50:18.467+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:50:19.148+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:50:19.138+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:50:19.151+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:50:19.203+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.748 seconds
[2022-12-15T12:50:49.544+0000] {processor.py:153} INFO - Started process (PID=10013) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:50:49.546+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:50:49.548+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:50:49.548+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:50:50.049+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:50:50.039+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:50:50.052+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:50:50.091+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.558 seconds
[2022-12-15T12:51:20.256+0000] {processor.py:153} INFO - Started process (PID=10248) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:51:20.258+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:51:20.260+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:51:20.259+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:51:20.863+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:51:20.854+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:51:20.865+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:51:20.901+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.652 seconds
[2022-12-15T12:51:51.095+0000] {processor.py:153} INFO - Started process (PID=10485) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:51:51.097+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:51:51.098+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:51:51.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:51:51.665+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:51:51.656+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:51:51.667+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:51:51.702+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.613 seconds
[2022-12-15T12:52:21.875+0000] {processor.py:153} INFO - Started process (PID=10726) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:52:21.877+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:52:21.878+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:52:21.878+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:52:22.679+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:52:22.670+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:52:22.681+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:52:22.721+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.851 seconds
[2022-12-15T12:52:53.706+0000] {processor.py:153} INFO - Started process (PID=10969) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:52:53.708+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:52:53.711+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:52:53.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:52:54.233+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:52:54.223+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:52:54.235+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:52:54.268+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.571 seconds
[2022-12-15T12:53:24.586+0000] {processor.py:153} INFO - Started process (PID=11204) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:53:24.588+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:53:24.590+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:53:24.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:53:25.145+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:53:25.134+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:53:25.148+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:53:25.284+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.704 seconds
[2022-12-15T12:53:55.871+0000] {processor.py:153} INFO - Started process (PID=11433) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:53:55.873+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:53:55.874+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:53:55.874+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:53:56.362+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:53:56.352+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:53:56.365+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:53:56.403+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.537 seconds
[2022-12-15T12:54:27.271+0000] {processor.py:153} INFO - Started process (PID=11662) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:54:27.273+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T12:54:27.274+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:54:27.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:54:27.851+0000] {logging_mixin.py:137} INFO - [2022-12-15T12:54:27.841+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T12:54:27.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T12:54:27.894+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.629 seconds
[2022-12-15T13:01:24.510+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:01:24.512+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:01:24.514+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:01:24.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:01:26.366+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:01:26.358+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:01:26.370+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:01:26.411+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 1.907 seconds
[2022-12-15T13:01:56.686+0000] {processor.py:153} INFO - Started process (PID=447) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:01:56.688+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:01:56.689+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:01:56.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:01:57.170+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:01:57.161+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:01:57.173+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:01:57.210+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.529 seconds
[2022-12-15T13:02:27.714+0000] {processor.py:153} INFO - Started process (PID=675) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:02:27.715+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:02:27.717+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:02:27.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:02:28.243+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:02:28.233+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:02:28.245+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:02:28.278+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.571 seconds
[2022-12-15T13:06:04.682+0000] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:06:04.685+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:06:04.687+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:06:04.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:06:05.793+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:06:05.786+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:06:05.796+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:06:05.826+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 1.152 seconds
[2022-12-15T13:06:36.036+0000] {processor.py:153} INFO - Started process (PID=433) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:06:36.038+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:06:36.039+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:06:36.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:06:36.512+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:06:36.504+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:06:36.515+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:06:36.547+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.517 seconds
[2022-12-15T13:07:06.661+0000] {processor.py:153} INFO - Started process (PID=664) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:07:06.663+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:07:06.664+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:07:06.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:07:07.138+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:07:07.129+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:07:07.141+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:07:07.172+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.516 seconds
[2022-12-15T13:08:55.027+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:08:55.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:08:55.031+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:08:55.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:08:56.826+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:08:56.820+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:08:56.828+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:08:56.855+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 1.835 seconds
[2022-12-15T13:09:26.972+0000] {processor.py:153} INFO - Started process (PID=431) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:09:26.974+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:09:26.975+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:09:26.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:09:27.574+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:09:27.565+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:09:27.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:09:27.615+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.649 seconds
[2022-12-15T13:24:27.275+0000] {processor.py:153} INFO - Started process (PID=188) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:24:27.277+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:24:27.279+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:24:27.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:24:29.025+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:24:29.017+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:24:29.027+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:24:29.055+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 1.787 seconds
[2022-12-15T13:24:59.203+0000] {processor.py:153} INFO - Started process (PID=442) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:24:59.206+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:24:59.208+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:24:59.207+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:25:00.052+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:25:00.039+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:25:00.056+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:25:00.094+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.897 seconds
[2022-12-15T13:25:30.322+0000] {processor.py:153} INFO - Started process (PID=671) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:25:30.323+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:25:30.325+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:25:30.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:25:30.821+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:25:30.812+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:25:30.824+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:25:30.863+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.546 seconds
[2022-12-15T13:26:01.131+0000] {processor.py:153} INFO - Started process (PID=909) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:26:01.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:26:01.134+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:26:01.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:26:01.604+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:26:01.596+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:26:01.607+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:26:01.643+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.518 seconds
[2022-12-15T13:26:32.365+0000] {processor.py:153} INFO - Started process (PID=1146) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:26:32.366+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:26:32.368+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:26:32.368+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:26:32.874+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:26:32.865+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:26:32.877+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:26:32.907+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.547 seconds
[2022-12-15T13:27:02.962+0000] {processor.py:153} INFO - Started process (PID=1387) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:27:02.964+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:27:02.966+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:27:02.966+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:27:03.529+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:27:03.521+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:27:03.532+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:27:03.562+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.608 seconds
[2022-12-15T13:27:34.296+0000] {processor.py:153} INFO - Started process (PID=1613) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:27:34.297+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:27:34.298+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:27:34.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:27:34.926+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:27:34.916+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:27:34.929+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:27:34.966+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.675 seconds
[2022-12-15T13:28:05.103+0000] {processor.py:153} INFO - Started process (PID=1842) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:28:05.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:28:05.106+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:28:05.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:28:05.591+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:28:05.582+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:28:05.594+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:28:05.623+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.526 seconds
[2022-12-15T13:28:35.894+0000] {processor.py:153} INFO - Started process (PID=2071) to work on /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:28:35.896+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/titanic_etl.py for tasks to queue
[2022-12-15T13:28:35.898+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:28:35.898+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:28:36.596+0000] {logging_mixin.py:137} INFO - [2022-12-15T13:28:36.587+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/titanic_etl.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/titanic_etl.py", line 9, in <module>
    from sklearn import preprocessing
ModuleNotFoundError: No module named 'sklearn'
[2022-12-15T13:28:36.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/titanic_etl.py
[2022-12-15T13:28:36.640+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/titanic_etl.py took 0.753 seconds
